//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWS_4_WF.Simplex_TVN {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://TVN/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        private int kField;
        
        private float fField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                if ((this.kField.Equals(value) != true)) {
                    this.kField = value;
                    this.RaisePropertyChanged("k");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TVN/", ConfigurationName="Simplex_TVN.SimplexSoap")]
    public interface SimplexSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TVN/Add", ReplyAction="*")]
        int Add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TVN/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int x, int y);
        
        // CODEGEN: Контракт генерации сообщений с именем s из пространства имен http://TVN/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://TVN/Concat", ReplyAction="*")]
        PWS_4_WF.Simplex_TVN.ConcatResponse Concat(PWS_4_WF.Simplex_TVN.ConcatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TVN/Concat", ReplyAction="*")]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_TVN.ConcatResponse> ConcatAsync(PWS_4_WF.Simplex_TVN.ConcatRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем a1 из пространства имен http://TVN/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://TVN/Sum", ReplyAction="*")]
        PWS_4_WF.Simplex_TVN.SumResponse Sum(PWS_4_WF.Simplex_TVN.SumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TVN/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_TVN.SumResponse> SumAsync(PWS_4_WF.Simplex_TVN.SumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TVN/Adds", ReplyAction="*")]
        int Adds(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TVN/Adds", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddsAsync(int x, int y);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConcatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Concat", Namespace="http://TVN/", Order=0)]
        public PWS_4_WF.Simplex_TVN.ConcatRequestBody Body;
        
        public ConcatRequest() {
        }
        
        public ConcatRequest(PWS_4_WF.Simplex_TVN.ConcatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://TVN/")]
    public partial class ConcatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double d;
        
        public ConcatRequestBody() {
        }
        
        public ConcatRequestBody(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConcatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConcatResponse", Namespace="http://TVN/", Order=0)]
        public PWS_4_WF.Simplex_TVN.ConcatResponseBody Body;
        
        public ConcatResponse() {
        }
        
        public ConcatResponse(PWS_4_WF.Simplex_TVN.ConcatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://TVN/")]
    public partial class ConcatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConcatResult;
        
        public ConcatResponseBody() {
        }
        
        public ConcatResponseBody(string ConcatResult) {
            this.ConcatResult = ConcatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sum", Namespace="http://TVN/", Order=0)]
        public PWS_4_WF.Simplex_TVN.SumRequestBody Body;
        
        public SumRequest() {
        }
        
        public SumRequest(PWS_4_WF.Simplex_TVN.SumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://TVN/")]
    public partial class SumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PWS_4_WF.Simplex_TVN.A a1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PWS_4_WF.Simplex_TVN.A a2;
        
        public SumRequestBody() {
        }
        
        public SumRequestBody(PWS_4_WF.Simplex_TVN.A a1, PWS_4_WF.Simplex_TVN.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumResponse", Namespace="http://TVN/", Order=0)]
        public PWS_4_WF.Simplex_TVN.SumResponseBody Body;
        
        public SumResponse() {
        }
        
        public SumResponse(PWS_4_WF.Simplex_TVN.SumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://TVN/")]
    public partial class SumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PWS_4_WF.Simplex_TVN.A SumResult;
        
        public SumResponseBody() {
        }
        
        public SumResponseBody(PWS_4_WF.Simplex_TVN.A SumResult) {
            this.SumResult = SumResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : PWS_4_WF.Simplex_TVN.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<PWS_4_WF.Simplex_TVN.SimplexSoap>, PWS_4_WF.Simplex_TVN.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int x, int y) {
            return base.Channel.Add(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int x, int y) {
            return base.Channel.AddAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWS_4_WF.Simplex_TVN.ConcatResponse PWS_4_WF.Simplex_TVN.SimplexSoap.Concat(PWS_4_WF.Simplex_TVN.ConcatRequest request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            PWS_4_WF.Simplex_TVN.ConcatRequest inValue = new PWS_4_WF.Simplex_TVN.ConcatRequest();
            inValue.Body = new PWS_4_WF.Simplex_TVN.ConcatRequestBody();
            inValue.Body.s = s;
            inValue.Body.d = d;
            PWS_4_WF.Simplex_TVN.ConcatResponse retVal = ((PWS_4_WF.Simplex_TVN.SimplexSoap)(this)).Concat(inValue);
            return retVal.Body.ConcatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_TVN.ConcatResponse> PWS_4_WF.Simplex_TVN.SimplexSoap.ConcatAsync(PWS_4_WF.Simplex_TVN.ConcatRequest request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<PWS_4_WF.Simplex_TVN.ConcatResponse> ConcatAsync(string s, double d) {
            PWS_4_WF.Simplex_TVN.ConcatRequest inValue = new PWS_4_WF.Simplex_TVN.ConcatRequest();
            inValue.Body = new PWS_4_WF.Simplex_TVN.ConcatRequestBody();
            inValue.Body.s = s;
            inValue.Body.d = d;
            return ((PWS_4_WF.Simplex_TVN.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWS_4_WF.Simplex_TVN.SumResponse PWS_4_WF.Simplex_TVN.SimplexSoap.Sum(PWS_4_WF.Simplex_TVN.SumRequest request) {
            return base.Channel.Sum(request);
        }
        
        public PWS_4_WF.Simplex_TVN.A Sum(PWS_4_WF.Simplex_TVN.A a1, PWS_4_WF.Simplex_TVN.A a2) {
            PWS_4_WF.Simplex_TVN.SumRequest inValue = new PWS_4_WF.Simplex_TVN.SumRequest();
            inValue.Body = new PWS_4_WF.Simplex_TVN.SumRequestBody();
            inValue.Body.a1 = a1;
            inValue.Body.a2 = a2;
            PWS_4_WF.Simplex_TVN.SumResponse retVal = ((PWS_4_WF.Simplex_TVN.SimplexSoap)(this)).Sum(inValue);
            return retVal.Body.SumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_TVN.SumResponse> PWS_4_WF.Simplex_TVN.SimplexSoap.SumAsync(PWS_4_WF.Simplex_TVN.SumRequest request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<PWS_4_WF.Simplex_TVN.SumResponse> SumAsync(PWS_4_WF.Simplex_TVN.A a1, PWS_4_WF.Simplex_TVN.A a2) {
            PWS_4_WF.Simplex_TVN.SumRequest inValue = new PWS_4_WF.Simplex_TVN.SumRequest();
            inValue.Body = new PWS_4_WF.Simplex_TVN.SumRequestBody();
            inValue.Body.a1 = a1;
            inValue.Body.a2 = a2;
            return ((PWS_4_WF.Simplex_TVN.SimplexSoap)(this)).SumAsync(inValue);
        }
        
        public int Adds(int x, int y) {
            return base.Channel.Adds(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddsAsync(int x, int y) {
            return base.Channel.AddsAsync(x, y);
        }
    }
}
