//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 
namespace WebServices.SimplexS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Web.Services.WebServiceAttribute(Namespace="http://VSA/")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SimplexSoap", Namespace="http://VSA/")]
    public abstract partial class Simplex : System.Web.Services.WebService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://VSA/ASMX.ADD", RequestElementName="ASMX.ADD", RequestNamespace="http://VSA/", ResponseElementName="ASMX.ADDResponse", ResponseNamespace="http://VSA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ASMX.ADDResult")]
        public abstract int Add(int x, int y);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://VSA/ASMX.CONCAT", RequestElementName="ASMX.CONCAT", RequestNamespace="http://VSA/", ResponseElementName="ASMX.CONCATResponse", ResponseNamespace="http://VSA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ASMX.CONCATResult")]
        public abstract string Concat(string s, double d);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://VSA/ASMX.SUM", RequestElementName="ASMX.SUM", RequestNamespace="http://VSA/", ResponseElementName="ASMX.SUMResponse", ResponseNamespace="http://VSA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ASMX.SUMResult")]
        public abstract A Sum(A a1, A a2);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://VSA/ASMX.ADDS", RequestElementName="ASMX.ADDS", RequestNamespace="http://VSA/", ResponseElementName="ASMX.ADDSResponse", ResponseNamespace="http://VSA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ASMX.ADDSResult")]
        public abstract int Adds(int x, int y);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://VSA/")]
    public partial class A {
        
        private string sField;
        
        private int kField;
        
        private float fField;
        
        /// <remarks/>
        public string s {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
            }
        }
        
        /// <remarks/>
        public int k {
            get {
                return this.kField;
            }
            set {
                this.kField = value;
            }
        }
        
        /// <remarks/>
        public float f {
            get {
                return this.fField;
            }
            set {
                this.fField = value;
            }
        }
    }


    public class SimplexImplemetation : Simplex
    {
        [return: XmlElement("ASMX.ADDResult")]
        public override int Add(int x, int y)
        {
            return x + y;
        }

        [return: XmlElement("ASMX.ADDSResult")]
        public override int Adds(int x, int y)
        {
            return x + y;
        }

        [return: XmlElement("ASMX.CONCATResult")]
        public override string Concat(string s, double d)
        {
           return s + d.ToString();
        }

        [return: XmlElement("ASMX.SUMResult")]
        public override A Sum(A a1, A a2)
        {
            return new A
            {
                s = a1.s + a2.s,
                k = a1.k + a2.k,
                f = a1.f + a2.f
            };
        }
    }
}
