//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWS_4_WF.Simplex_VSA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://VSA/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        private int kField;
        
        private float fField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                if ((this.kField.Equals(value) != true)) {
                    this.kField = value;
                    this.RaisePropertyChanged("k");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://VSA/", ConfigurationName="Simplex_VSA.SimplexSoap")]
    public interface SimplexSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (ASMX.ADD) of message ASMX.ADD does not match the default value (Add)
        [System.ServiceModel.OperationContractAttribute(Action="http://VSA/ASMX.ADD", ReplyAction="*")]
        PWS_4_WF.Simplex_VSA.ASMXADD1 Add(PWS_4_WF.Simplex_VSA.ASMXADD request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://VSA/ASMX.ADD", ReplyAction="*")]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXADD1> AddAsync(PWS_4_WF.Simplex_VSA.ASMXADD request);
        
        // CODEGEN: Generating message contract since the wrapper name (ASMX.CONCAT) of message ASMX.CONCAT does not match the default value (Concat)
        [System.ServiceModel.OperationContractAttribute(Action="http://VSA/ASMX.CONCAT", ReplyAction="*")]
        PWS_4_WF.Simplex_VSA.ASMXCONCAT1 Concat(PWS_4_WF.Simplex_VSA.ASMXCONCAT request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://VSA/ASMX.CONCAT", ReplyAction="*")]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXCONCAT1> ConcatAsync(PWS_4_WF.Simplex_VSA.ASMXCONCAT request);
        
        // CODEGEN: Generating message contract since the wrapper name (ASMX.SUM) of message ASMX.SUM does not match the default value (Sum)
        [System.ServiceModel.OperationContractAttribute(Action="http://VSA/ASMX.SUM", ReplyAction="*")]
        PWS_4_WF.Simplex_VSA.ASMXSUM1 Sum(PWS_4_WF.Simplex_VSA.ASMXSUM request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://VSA/ASMX.SUM", ReplyAction="*")]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXSUM1> SumAsync(PWS_4_WF.Simplex_VSA.ASMXSUM request);
        
        // CODEGEN: Generating message contract since the wrapper name (ASMX.ADDS) of message ASMX.ADDS does not match the default value (Adds)
        [System.ServiceModel.OperationContractAttribute(Action="http://VSA/ASMX.ADDS", ReplyAction="*")]
        PWS_4_WF.Simplex_VSA.ASMXADDS1 Adds(PWS_4_WF.Simplex_VSA.ASMXADDS request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://VSA/ASMX.ADDS", ReplyAction="*")]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXADDS1> AddsAsync(PWS_4_WF.Simplex_VSA.ASMXADDS request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ASMX.ADD", WrapperNamespace="http://VSA/", IsWrapped=true)]
    public partial class ASMXADD {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VSA/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VSA/", Order=1)]
        public int y;
        
        public ASMXADD() {
        }
        
        public ASMXADD(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ASMX.ADDResponse", WrapperNamespace="http://VSA/", IsWrapped=true)]
    public partial class ASMXADD1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ASMX.ADDResult", Namespace="http://VSA/", Order=0)]
        public int ASMXADDResult;
        
        public ASMXADD1() {
        }
        
        public ASMXADD1(int ASMXADDResult) {
            this.ASMXADDResult = ASMXADDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ASMX.CONCAT", WrapperNamespace="http://VSA/", IsWrapped=true)]
    public partial class ASMXCONCAT {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VSA/", Order=0)]
        public string s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VSA/", Order=1)]
        public double d;
        
        public ASMXCONCAT() {
        }
        
        public ASMXCONCAT(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ASMX.CONCATResponse", WrapperNamespace="http://VSA/", IsWrapped=true)]
    public partial class ASMXCONCAT1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ASMX.CONCATResult", Namespace="http://VSA/", Order=0)]
        public string ASMXCONCATResult;
        
        public ASMXCONCAT1() {
        }
        
        public ASMXCONCAT1(string ASMXCONCATResult) {
            this.ASMXCONCATResult = ASMXCONCATResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ASMX.SUM", WrapperNamespace="http://VSA/", IsWrapped=true)]
    public partial class ASMXSUM {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VSA/", Order=0)]
        public PWS_4_WF.Simplex_VSA.A a1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VSA/", Order=1)]
        public PWS_4_WF.Simplex_VSA.A a2;
        
        public ASMXSUM() {
        }
        
        public ASMXSUM(PWS_4_WF.Simplex_VSA.A a1, PWS_4_WF.Simplex_VSA.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ASMX.SUMResponse", WrapperNamespace="http://VSA/", IsWrapped=true)]
    public partial class ASMXSUM1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ASMX.SUMResult", Namespace="http://VSA/", Order=0)]
        public PWS_4_WF.Simplex_VSA.A ASMXSUMResult;
        
        public ASMXSUM1() {
        }
        
        public ASMXSUM1(PWS_4_WF.Simplex_VSA.A ASMXSUMResult) {
            this.ASMXSUMResult = ASMXSUMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ASMX.ADDS", WrapperNamespace="http://VSA/", IsWrapped=true)]
    public partial class ASMXADDS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VSA/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VSA/", Order=1)]
        public int y;
        
        public ASMXADDS() {
        }
        
        public ASMXADDS(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ASMX.ADDSResponse", WrapperNamespace="http://VSA/", IsWrapped=true)]
    public partial class ASMXADDS1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ASMX.ADDSResult", Namespace="http://VSA/", Order=0)]
        public int ASMXADDSResult;
        
        public ASMXADDS1() {
        }
        
        public ASMXADDS1(int ASMXADDSResult) {
            this.ASMXADDSResult = ASMXADDSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : PWS_4_WF.Simplex_VSA.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<PWS_4_WF.Simplex_VSA.SimplexSoap>, PWS_4_WF.Simplex_VSA.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWS_4_WF.Simplex_VSA.ASMXADD1 PWS_4_WF.Simplex_VSA.SimplexSoap.Add(PWS_4_WF.Simplex_VSA.ASMXADD request) {
            return base.Channel.Add(request);
        }
        
        public int Add(int x, int y) {
            PWS_4_WF.Simplex_VSA.ASMXADD inValue = new PWS_4_WF.Simplex_VSA.ASMXADD();
            inValue.x = x;
            inValue.y = y;
            PWS_4_WF.Simplex_VSA.ASMXADD1 retVal = ((PWS_4_WF.Simplex_VSA.SimplexSoap)(this)).Add(inValue);
            return retVal.ASMXADDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXADD1> PWS_4_WF.Simplex_VSA.SimplexSoap.AddAsync(PWS_4_WF.Simplex_VSA.ASMXADD request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXADD1> AddAsync(int x, int y) {
            PWS_4_WF.Simplex_VSA.ASMXADD inValue = new PWS_4_WF.Simplex_VSA.ASMXADD();
            inValue.x = x;
            inValue.y = y;
            return ((PWS_4_WF.Simplex_VSA.SimplexSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWS_4_WF.Simplex_VSA.ASMXCONCAT1 PWS_4_WF.Simplex_VSA.SimplexSoap.Concat(PWS_4_WF.Simplex_VSA.ASMXCONCAT request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            PWS_4_WF.Simplex_VSA.ASMXCONCAT inValue = new PWS_4_WF.Simplex_VSA.ASMXCONCAT();
            inValue.s = s;
            inValue.d = d;
            PWS_4_WF.Simplex_VSA.ASMXCONCAT1 retVal = ((PWS_4_WF.Simplex_VSA.SimplexSoap)(this)).Concat(inValue);
            return retVal.ASMXCONCATResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXCONCAT1> PWS_4_WF.Simplex_VSA.SimplexSoap.ConcatAsync(PWS_4_WF.Simplex_VSA.ASMXCONCAT request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXCONCAT1> ConcatAsync(string s, double d) {
            PWS_4_WF.Simplex_VSA.ASMXCONCAT inValue = new PWS_4_WF.Simplex_VSA.ASMXCONCAT();
            inValue.s = s;
            inValue.d = d;
            return ((PWS_4_WF.Simplex_VSA.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWS_4_WF.Simplex_VSA.ASMXSUM1 PWS_4_WF.Simplex_VSA.SimplexSoap.Sum(PWS_4_WF.Simplex_VSA.ASMXSUM request) {
            return base.Channel.Sum(request);
        }
        
        public PWS_4_WF.Simplex_VSA.A Sum(PWS_4_WF.Simplex_VSA.A a1, PWS_4_WF.Simplex_VSA.A a2) {
            PWS_4_WF.Simplex_VSA.ASMXSUM inValue = new PWS_4_WF.Simplex_VSA.ASMXSUM();
            inValue.a1 = a1;
            inValue.a2 = a2;
            PWS_4_WF.Simplex_VSA.ASMXSUM1 retVal = ((PWS_4_WF.Simplex_VSA.SimplexSoap)(this)).Sum(inValue);
            return retVal.ASMXSUMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXSUM1> PWS_4_WF.Simplex_VSA.SimplexSoap.SumAsync(PWS_4_WF.Simplex_VSA.ASMXSUM request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXSUM1> SumAsync(PWS_4_WF.Simplex_VSA.A a1, PWS_4_WF.Simplex_VSA.A a2) {
            PWS_4_WF.Simplex_VSA.ASMXSUM inValue = new PWS_4_WF.Simplex_VSA.ASMXSUM();
            inValue.a1 = a1;
            inValue.a2 = a2;
            return ((PWS_4_WF.Simplex_VSA.SimplexSoap)(this)).SumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWS_4_WF.Simplex_VSA.ASMXADDS1 PWS_4_WF.Simplex_VSA.SimplexSoap.Adds(PWS_4_WF.Simplex_VSA.ASMXADDS request) {
            return base.Channel.Adds(request);
        }
        
        public int Adds(int x, int y) {
            PWS_4_WF.Simplex_VSA.ASMXADDS inValue = new PWS_4_WF.Simplex_VSA.ASMXADDS();
            inValue.x = x;
            inValue.y = y;
            PWS_4_WF.Simplex_VSA.ASMXADDS1 retVal = ((PWS_4_WF.Simplex_VSA.SimplexSoap)(this)).Adds(inValue);
            return retVal.ASMXADDSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXADDS1> PWS_4_WF.Simplex_VSA.SimplexSoap.AddsAsync(PWS_4_WF.Simplex_VSA.ASMXADDS request) {
            return base.Channel.AddsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PWS_4_WF.Simplex_VSA.ASMXADDS1> AddsAsync(int x, int y) {
            PWS_4_WF.Simplex_VSA.ASMXADDS inValue = new PWS_4_WF.Simplex_VSA.ASMXADDS();
            inValue.x = x;
            inValue.y = y;
            return ((PWS_4_WF.Simplex_VSA.SimplexSoap)(this)).AddsAsync(inValue);
        }
    }
}
