//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWSLab_04_WinForms.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://vrl/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        private int kField;
        
        private float fField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                if ((this.kField.Equals(value) != true)) {
                    this.kField = value;
                    this.RaisePropertyChanged("k");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vrl/", ConfigurationName="WS.SimplexSoap")]
    public interface SimplexSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (add) сообщения add не соответствует значению по умолчанию (Add).
        [System.ServiceModel.OperationContractAttribute(Action="http://vrl/add", ReplyAction="*")]
        PWSLab_04_WinForms.WS.add1 Add(PWSLab_04_WinForms.WS.add request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vrl/add", ReplyAction="*")]
        System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.add1> AddAsync(PWSLab_04_WinForms.WS.add request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (concat) сообщения concat не соответствует значению по умолчанию (Concat).
        [System.ServiceModel.OperationContractAttribute(Action="http://vrl/concat", ReplyAction="*")]
        PWSLab_04_WinForms.WS.concat1 Concat(PWSLab_04_WinForms.WS.concat request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vrl/concat", ReplyAction="*")]
        System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.concat1> ConcatAsync(PWSLab_04_WinForms.WS.concat request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (sum) сообщения sum не соответствует значению по умолчанию (Sum).
        [System.ServiceModel.OperationContractAttribute(Action="http://vrl/sum", ReplyAction="*")]
        PWSLab_04_WinForms.WS.sum1 Sum(PWSLab_04_WinForms.WS.sum request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vrl/sum", ReplyAction="*")]
        System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.sum1> SumAsync(PWSLab_04_WinForms.WS.sum request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (adds) сообщения adds не соответствует значению по умолчанию (Adds).
        [System.ServiceModel.OperationContractAttribute(Action="http://vrl/adds", ReplyAction="*")]
        PWSLab_04_WinForms.WS.adds1 Adds(PWSLab_04_WinForms.WS.adds request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vrl/adds", ReplyAction="*")]
        System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.adds1> AddsAsync(PWSLab_04_WinForms.WS.adds request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://vrl/", IsWrapped=true)]
    public partial class add {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=1)]
        public int y;
        
        public add() {
        }
        
        public add(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://vrl/", IsWrapped=true)]
    public partial class add1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=0)]
        public int addResult;
        
        public add1() {
        }
        
        public add1(int addResult) {
            this.addResult = addResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="concat", WrapperNamespace="http://vrl/", IsWrapped=true)]
    public partial class concat {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=0)]
        public string s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=1)]
        public double d;
        
        public concat() {
        }
        
        public concat(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="concatResponse", WrapperNamespace="http://vrl/", IsWrapped=true)]
    public partial class concat1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=0)]
        public string concatResult;
        
        public concat1() {
        }
        
        public concat1(string concatResult) {
            this.concatResult = concatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sum", WrapperNamespace="http://vrl/", IsWrapped=true)]
    public partial class sum {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=0)]
        public PWSLab_04_WinForms.WS.A a1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=1)]
        public PWSLab_04_WinForms.WS.A a2;
        
        public sum() {
        }
        
        public sum(PWSLab_04_WinForms.WS.A a1, PWSLab_04_WinForms.WS.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumResponse", WrapperNamespace="http://vrl/", IsWrapped=true)]
    public partial class sum1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=0)]
        public PWSLab_04_WinForms.WS.A sumResult;
        
        public sum1() {
        }
        
        public sum1(PWSLab_04_WinForms.WS.A sumResult) {
            this.sumResult = sumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="adds", WrapperNamespace="http://vrl/", IsWrapped=true)]
    public partial class adds {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=1)]
        public int y;
        
        public adds() {
        }
        
        public adds(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addsResponse", WrapperNamespace="http://vrl/", IsWrapped=true)]
    public partial class adds1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vrl/", Order=0)]
        public int addsResult;
        
        public adds1() {
        }
        
        public adds1(int addsResult) {
            this.addsResult = addsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : PWSLab_04_WinForms.WS.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<PWSLab_04_WinForms.WS.SimplexSoap>, PWSLab_04_WinForms.WS.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWSLab_04_WinForms.WS.add1 PWSLab_04_WinForms.WS.SimplexSoap.Add(PWSLab_04_WinForms.WS.add request) {
            return base.Channel.Add(request);
        }
        
        public int Add(int x, int y) {
            PWSLab_04_WinForms.WS.add inValue = new PWSLab_04_WinForms.WS.add();
            inValue.x = x;
            inValue.y = y;
            PWSLab_04_WinForms.WS.add1 retVal = ((PWSLab_04_WinForms.WS.SimplexSoap)(this)).Add(inValue);
            return retVal.addResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.add1> PWSLab_04_WinForms.WS.SimplexSoap.AddAsync(PWSLab_04_WinForms.WS.add request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.add1> AddAsync(int x, int y) {
            PWSLab_04_WinForms.WS.add inValue = new PWSLab_04_WinForms.WS.add();
            inValue.x = x;
            inValue.y = y;
            return ((PWSLab_04_WinForms.WS.SimplexSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWSLab_04_WinForms.WS.concat1 PWSLab_04_WinForms.WS.SimplexSoap.Concat(PWSLab_04_WinForms.WS.concat request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            PWSLab_04_WinForms.WS.concat inValue = new PWSLab_04_WinForms.WS.concat();
            inValue.s = s;
            inValue.d = d;
            PWSLab_04_WinForms.WS.concat1 retVal = ((PWSLab_04_WinForms.WS.SimplexSoap)(this)).Concat(inValue);
            return retVal.concatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.concat1> PWSLab_04_WinForms.WS.SimplexSoap.ConcatAsync(PWSLab_04_WinForms.WS.concat request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.concat1> ConcatAsync(string s, double d) {
            PWSLab_04_WinForms.WS.concat inValue = new PWSLab_04_WinForms.WS.concat();
            inValue.s = s;
            inValue.d = d;
            return ((PWSLab_04_WinForms.WS.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWSLab_04_WinForms.WS.sum1 PWSLab_04_WinForms.WS.SimplexSoap.Sum(PWSLab_04_WinForms.WS.sum request) {
            return base.Channel.Sum(request);
        }
        
        public PWSLab_04_WinForms.WS.A Sum(PWSLab_04_WinForms.WS.A a1, PWSLab_04_WinForms.WS.A a2) {
            PWSLab_04_WinForms.WS.sum inValue = new PWSLab_04_WinForms.WS.sum();
            inValue.a1 = a1;
            inValue.a2 = a2;
            PWSLab_04_WinForms.WS.sum1 retVal = ((PWSLab_04_WinForms.WS.SimplexSoap)(this)).Sum(inValue);
            return retVal.sumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.sum1> PWSLab_04_WinForms.WS.SimplexSoap.SumAsync(PWSLab_04_WinForms.WS.sum request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.sum1> SumAsync(PWSLab_04_WinForms.WS.A a1, PWSLab_04_WinForms.WS.A a2) {
            PWSLab_04_WinForms.WS.sum inValue = new PWSLab_04_WinForms.WS.sum();
            inValue.a1 = a1;
            inValue.a2 = a2;
            return ((PWSLab_04_WinForms.WS.SimplexSoap)(this)).SumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWSLab_04_WinForms.WS.adds1 PWSLab_04_WinForms.WS.SimplexSoap.Adds(PWSLab_04_WinForms.WS.adds request) {
            return base.Channel.Adds(request);
        }
        
        public int Adds(int x, int y) {
            PWSLab_04_WinForms.WS.adds inValue = new PWSLab_04_WinForms.WS.adds();
            inValue.x = x;
            inValue.y = y;
            PWSLab_04_WinForms.WS.adds1 retVal = ((PWSLab_04_WinForms.WS.SimplexSoap)(this)).Adds(inValue);
            return retVal.addsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.adds1> PWSLab_04_WinForms.WS.SimplexSoap.AddsAsync(PWSLab_04_WinForms.WS.adds request) {
            return base.Channel.AddsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PWSLab_04_WinForms.WS.adds1> AddsAsync(int x, int y) {
            PWSLab_04_WinForms.WS.adds inValue = new PWSLab_04_WinForms.WS.adds();
            inValue.x = x;
            inValue.y = y;
            return ((PWSLab_04_WinForms.WS.SimplexSoap)(this)).AddsAsync(inValue);
        }
    }
}
